version: '3.8'

services:
  mysql:
    image: mysql
    container_name: mobile-shop-mysql-prod
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_prod_data:/var/lib/mysql
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

  api:
    image: wilde123569/mobile-shop-api-prod:latest
    build:
      context: ./apps/api
    container_name: mobile-shop-api-prod
    restart: unless-stopped
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - mysql
    environment:
      # Sửa DB_HOST thành "mysql" (tên của service bên trên) để các container chui vào nhau
      DB_HOST: mysql 
      DB_PORT: 3306
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      SERVER_PORT: ${SERVER_PORT}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_ORIGIN: ${FRONTEND_ORIGIN}
      APP_ENV: ${APP_ENV}

  web:
    image: wilde123569/mobile-shop-web-prod:latest
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      # Truyền biến vào lúc build Next.js
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_EMAILJS_PUBLIC_KEY: ${NEXT_PUBLIC_EMAILJS_PUBLIC_KEY}
    container_name: mobile-shop-web-prod
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  mysql_prod_data: