ALTER TABLE phones ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE invoices ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE repairs ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE warranties ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL;