ALTER TABLE warranties
ADD COLUMN customer_id INT NULL,
ADD COLUMN invoice_id INT NULL,
ADD COLUMN device_name VARCHAR(255) NULL,
ADD COLUMN imei VARCHAR(50) NULL,
ADD COLUMN description TEXT NULL,
ADD COLUMN technical_note TEXT NULL,
ADD COLUMN status VARCHAR(50) DEFAULT 'RECEIVED',
ADD COLUMN cost BIGINT DEFAULT 0,
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP;