-- Revert về DECIMAL(15,2) nếu rollback
ALTER TABLE phones 
MODIFY COLUMN purchase_price DECIMAL(15,2) NOT NULL DEFAULT 0,
MODIFY COLUMN sale_price DECIMAL(15,2);

ALTER TABLE invoices 
MODIFY COLUMN total_amount DECIMAL(15,2) NOT NULL DEFAULT 0;

ALTER TABLE invoice_items 
MODIFY COLUMN unit_price DECIMAL(15,2) NOT NULL DEFAULT 0,
MODIFY COLUMN amount DECIMAL(15,2) NOT NULL DEFAULT 0;