name: Deploy Mobile Shop to AWS EC2

on:
  push:
    branches:
      - main # Push code lên nhánh main là tự động chạy

jobs:
  # GIAI ĐOẠN 1: BẮT MÁY CHỦ GITHUB BUILD VÀ ĐẨY LÊN KHO
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout code
        uses: actions/checkout@v3

      - name: 2. Đăng nhập vào Kho Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 3. Build & Push API Image
        uses: docker/build-push-action@v4
        with:
          context: ./apps/api  # Đường dẫn tới thư mục API (Sửa nếu cần)
          file: ./apps/api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mobile-shop-api:latest

      - name: 4. Build & Push Web Image
        uses: docker/build-push-action@v4
        with:
          context: ./apps/web  # Đường dẫn tới thư mục Web (Sửa nếu cần)
          file: ./apps/web/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mobile-shop-web:latest

  # GIAI ĐOẠN 2: CHUI VÀO EC2 KÉO CODE VỀ CHẠY
  deploy-to-ec2:
    needs: build-and-push-images # Phải đợi giai đoạn 1 xong mới chạy
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout code (để lấy file docker-compose)
        uses: actions/checkout@v3

      - name: 2. Bắn file docker-compose sang Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.prod.yml"
          target: "~/mobile-shop-mgmt/"

      - name: 3. Ra lệnh Server kéo Image và Chạy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/mobile-shop-mgmt
            
            # 1. Tạo file .env từ GitHub Secret để Server xài lúc chạy
            echo "${{ secrets.PROD_ENV_FILE }}" > .env
            
            # 2. Tải bản mới nhất từ kho về
            docker compose -f docker-compose.prod.yml pull
            
            # 3. Chạy lên (Lúc này compose sẽ tự động đọc file .env ở cùng thư mục)
            docker compose -f docker-compose.prod.yml up -d
            
            # 4. Xoá file .env đi để bảo mật (Docker đã ngậm biến vào bộ nhớ)
            rm -f .env
            
            # 5. Dọn rác Image bản cũ
            docker image prune -f